# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20190522_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='prof_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='prof_images/'),
        ),
    ]
