# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20190522_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
